import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { Card } from "../organisms/Card";
import { ThanksCard } from "../organisms/ThanksCard";

import React, { useState } from "react";

export const Home = () => {
  const [isSubmitted, setIsSubmitted] = useState<boolean>(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isSubmitted ? <ThanksCard /> : <Card />}
      </main>
    </div>
  );
};
